### ISSUE TITLE
Switcher doesn't change variant for Firefox and Files

### ISSUE THREAD

**Issue by hrvstr** [oktayacikalin/gtk-theme-variant-switcher#12]
Hi I am using elementary OS freya (0.3.1) and just installed your script and added two strings in dconf editor like this:

```
[('Navigator', 'dark', 'Firefox'), ('files', 'dark', 'Files')]
```

when I run the switcher in debug mode I get the following output

```
 ~/./s/gtk-theme-variant-switcher> ./switcher.py 
[switcher.on_activate.INFO] Listening for newly opened windows.
[switcher.update_window.DEBUG] Got window: navigator ("Firefox"/"mozilla firefox")
[switcher.update_window.INFO] Setting window "navigator" to "dark".

```

The problem is that Firefox and Files still are using the light theme variant.
How can I fix this?

**Comment by oktayacikalin** [comment]
Does this problem still apply?

**Comment by hrvstr** [comment]
Sorry, I don't use elementary OS anymore. Been years since my last install.
